{{- if not .Values.datadog.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "entitle-agent.fullname" . }}-datadog-config
data:
  conf.yaml: |
    init_config:
    instances:
    logs:
      - type: file
        path: /var/log/entitle-agent/*.log
        service: entitle-agent-onprem
        source: entitle-agent
        sourcecategory: sourcecode
{{- end }}
