apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "entitle-agent.fullname" . }}-datadog-secret
  labels:
  {{- include "entitle-agent.labels" . | nindent 4 }}
stringData:
{{- if .Values.datadog.enabled }}
  api-key: {{ include "entitle-agent.datadogApiKey" . | quote }}
{{- else }}
  DD_API_KEY: {{ include "entitle-agent.datadogApiKey" . | quote }}
{{- end }}
