apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "entitle-agent.fullname" . }}-deployment
  labels:
  {{- include "entitle-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
