apiVersion: v1
kind: Secret
metadata:
  name: {{ include "entitle-agent.fullname" . }}-docker-login
  labels:
  {{- include "entitle-agent.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ required "imageCredentials are required" .Values.imageCredentials | quote }}
type: kubernetes.io/dockerconfigjson
