{{- if or .Values.agent.websocket.token .Values.agent.kafka.token }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "entitle-agent.fullname" . }}-secret
  labels:
  {{- include "entitle-agent.labels" . | nindent 4 }}
stringData:
  {{- if eq .Values.agent.mode "websocket" }}
  TOKEN: {{ .Values.agent.websocket.token | quote }}
  {{- else if .Values.agent.kafka.token }}
  ENTITLE_JSON_CONFIGURATION: "{\"BASE64_CONFIGURATION\":\"{{ .Values.agent.kafka.token }}\"}"
  {{- end }}
{{- end }}
